AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app02

  Sample SAM Template for sam-app02
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
        Variables:
          REDIS_LOCAL_HOST: !Ref redis://172.17.0.2:6379
          AWS_ACCESS_KEY: !Ref AKIA4673VUVHW4WHVPN6
          AWS_SECRET_KEY: !Ref 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 #mcmVyJ/va7eQDa190INd7afQ6krjEO40Zh209b0h
Resources:
  InserInput:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: input.saveInput
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /saveInput
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - input.ts

  Output:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: output.saveInput
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /output/{id}
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - output.ts

  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable1
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  
  # InserInputApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # InserInput:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt InserInput.Arn
  # InserInputIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt InserInputRole.Arn
  OutputApi:
    Description: "API Gateway endpoint URL for Prod stage for Output LCR function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  Output:
    Description: "Output LCR Lambda Function ARN"
    Value: !GetAtt InserInput.Arn
  OutputIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt Output.Arn